INSERT INTO cases (
  case_id,
  case_version,
  patient_consent_status,
  patient_consent_timestamp,
  hospital_clinical_confirmation_status,
  hospital_confirmation_timestamp,
  member_id,
  policy_id,
  hospital_id,
  diagnosis,
  planned_procedure,
  planned_date,
  evidence_references,
  document_provenance,
  current_case_status,
  source_system,
  created_at,
  updated_at
) VALUES (
  'CASE-CT-REAL-001',
  1,
  true,
  '2026-08-16T18:05:00+05:30',
  true,
  '2026-08-16T18:10:00+05:30',
  'MBR-ASHA-1042',
  'CT-HEALTH-2026-001',
  'HSP-NIR-021',
  'Symptomatic cholelithiasis',
  'Laparoscopic cholecystectomy',
  '2026-08-24',
  '["CoverageTwin_Demo_Policy.pdf", "CoverageTwin_Demo_Clinical_Record.pdf", "CoverageTwin_Demo_Estimate_Contract.pdf"]'::jsonb,
  'VERIFIED',
  'WAITING_FOR_ACTIVATION',
  'coverage_twin_case_registry',
  now(),
  now()
)
ON CONFLICT (case_id) DO NOTHING;
